<x-layouts.app>
    @include("components.ourpillar.school-development.hero-banner")
    @include("components.ourpillar.school-development.overview")
    @include("components.ourpillar.school-development.discover-program")
    @include("components.transform")
    @include("components.ourpillar.school-development.partnership")
    @include("components.ourpillar.school-development.impression")
    @include("components.contact-us")
</x-layouts.app>
